{% set name = "itables" %}
{% set version = "2.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mwouts/itables/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6fa58a813e937bafaf7c0aa265a770d3dcfb58a55fe0b7d9e4175fdde78dab39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nodejs
    - python {{ python_min }}
    - python-build
    - hatch-jupyter-builder
    - dash
    - pyyaml
    - hatchling
    - pip
  run:
    - ipython
    - pandas
    - numpy
    - packaging
    - typing-extensions
    - python >={{ python_min }}

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mwouts/itables
  doc_url: https://mwouts.github.io/itables
  summary: Pandas and Polars DataFrames as Interactive DataTables
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt
    - LICENSE_datatables-net.txt
  description: |
    Render Pandas and Polars DataFrames as interactive [DataTables](https://datatables.net/)
    that you can sort, paginate, scroll or filter. ITables works in Jupyter, 
    VS Code, Google Colab, Quarto, Marimo, and in many application frameworks like 
    Dash, Panel, Shiny, or Streamlit.

extra:
  recipe-maintainers:
    - mwouts
    - asford
