{% set name = "itables" %}
{% set version = "2.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: ed96c98cdd91a91c004c1a0150d572a6b1021a1311bc94e8bfa2e68ba42d44fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nodejs
    - python >=3.8
    - python-build
    - hatch-jupyter-builder
    - hatchling
    - pip
  run:
    - ipython
    - pandas
    - numpy
    - python >=3.7

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  doc_url: https://mwouts.github.io/itables
  summary: Pandas and Polars DataFrames as Interactive DataTables
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt
    - LICENSE_datatables-net.txt
  description: |
    This packages changes how Pandas and Polars DataFrames are rendered in Jupyter Notebooks.
    With ITables you can display your tables as interactive [DataTables](https://datatables.net/)
    that you can sort, paginate, scroll or filter.

extra:
  recipe-maintainers:
    - mwouts
    - asford
