{% set name = "itables" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: ee33b201d83e136b26d7e9739db91f6ce801d52d1a9846dd6333f21322cd9e97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - pandas
    - python >=3.6

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Interactive Tables in Jupyter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
