{% set name = "itables" %}
{% set version = "1.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: 9904bc0d995141ce0cf2178c0cc330105ca2ed11ac0a245f911d9c6362cb6c73

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - requests
    - setuptools
  run:
    - ipython
    - pandas
    - numpy
    - python >=2.7

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Interactive Tables in Jupyter
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt

extra:
  recipe-maintainers:
    - mwouts
    - asford
