{% set name = "itables" %}
{% set version = "2.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: 838ed4783da0b6481b9062c362b8a331aa56f48d6c90e0f6dc76a0488a316049

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nodejs
    - python {{ python_min }}
    - python-build
    - hatch-jupyter-builder
    - hatchling
    - pip
  run:
    - ipython
    - pandas
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mwouts/itables
  doc_url: https://mwouts.github.io/itables
  summary: Pandas and Polars DataFrames as Interactive DataTables
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt
    - LICENSE_datatables-net.txt
  description: |
    This packages changes how Pandas and Polars DataFrames are rendered in Jupyter Notebooks.
    With ITables you can display your tables as interactive [DataTables](https://datatables.net/)
    that you can sort, paginate, scroll or filter.

extra:
  recipe-maintainers:
    - mwouts
    - asford
